spring:
  application:
    name: order

  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password: test

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

server:
  port: 19091

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/
  instance:
    hostname: localhost

logging:
  level:
    com:  # Package의 특정 클래스 로깅 레벨 설정
      nbcamp:
        course:
          feign:
            order:
              client:
                ProductClient: DEBUG # Feign logging은 DEBUG 에서만 동작함