spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**
        - id: order
          uri: lb://order
          predicates:
            - Path=/orders/**
        - id: product
          uri: lb://product
          predicates:
            - Path=/products/**


eureka:
  client:
    service-url:
      defaultZone: http://eureka:19090/eureka/

server:
  port: 8080